language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Rezantsev_All_Labs
  - make -j
  - ./Vector/Vector
  - ./VectorLib/VectorLib
  - ./Matrix/Matrix
  - ./MatrixLib/MatrixLib
  - ./test/test
notifications:
  email: false