language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Rezantsev_All_Labs
  - make -j
  - ./Polsk/Polsk
  - ./Polinom/Polinom
  - ./Vector/Vector
  - ./List/List
  - ./Matrix/Matrix
  - ./ArrayList/ArrayList
  - ./Queue/Queue
  - cd ./Stack
  - cd ./MStack
  - cd ./test
notifications:
  email: false
