language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Rezantsev_All_Labs
  - make -j
  - ./List/List
  - ./test/test
notifications:
  email: false
